name: Run Unit Test

on:
  push:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 현재 Repository 의 코드를 체크아웃
      # GitHub Actions에서 작업을 수행하기 위해 소스를 불러옴
      - name: Checkout to this repository
        uses: actions/checkout@v4

      # 실행할 환경에 Node.js 18버전 을 설정
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # yarn.lock 파일에 정의된 패키지 버전에 맞춰 의존성을 설치
      - name: Install dependencies from lock file
        run: yarn install --frozen-lockfile

      # @rollup/rollup-linux-x64-gnu 패키지를 설치
      # linux 환경 상, vitest 실행에 필요한 모듈 설치
      - name: Install additional dependencies
        run: yarn add @rollup/rollup-linux-x64-gnu@4.14.1

      # 테스트 코드 실행
      - name: Run test
        run: yarn test
